### ISSUE TITLE
Que 1.x breaks db:test:load_schema

### ISSUE THREAD

**Issue by a0s** [que-rb/que#306]
Found this behaviour:
```
> rspec
rails aborted!
ActiveRecord::StatementInvalid: PG::SyntaxError: ERROR:  syntax error at or near ")"
LINE 1: ...rgs) = 'array'::text), CONSTRAINT job_class_length CHECK ())
                                                                     ^
/Users/a0s/my/oh_my_product/db/schema.rb:19:in `block in <top (required)>'
/Users/a0s/my/oh_my_product/db/schema.rb:13:in `<top (required)>'

Caused by:
PG::SyntaxError: ERROR:  syntax error at or near ")"
LINE 1: ...rgs) = 'array'::text), CONSTRAINT job_class_length CHECK ())
                                                                     ^
/Users/a0s/my/oh_my_product/db/schema.rb:19:in `block in <top (required)>'
/Users/a0s/my/oh_my_product/db/schema.rb:13:in `<top (required)>'
Tasks: TOP => db:test:load_schema
(See full trace by running task with --trace)
Migrations are pending. To resolve this issue, run:

        bin/rails db:migrate RAILS_ENV=test

You have 10 pending migrations:

2021001000000_enable_uuid.rb
2021001000010_create_que_schema.rb
.... other migrations....
No examples found.
```

schema.rb:
```ruby
  create_table "que_jobs", comment: "4", force: :cascade do |t|
    t.integer "priority", limit: 2, default: 100, null: false
    t.datetime "run_at", default: -> { "now()" }, null: false
    t.text "job_class", null: false
    t.integer "error_count", default: 0, null: false
    t.text "last_error_message"
    t.text "queue", default: "default", null: false
    t.text "last_error_backtrace"
    t.datetime "finished_at"
    t.datetime "expired_at"
    t.jsonb "args", default: [], null: false
    t.jsonb "data", default: {}, null: false
    t.index ["args"], name: "que_jobs_args_gin_idx", opclass: :jsonb_path_ops, using: :gin
    t.index ["data"], name: "que_jobs_data_gin_idx", opclass: :jsonb_path_ops, using: :gin
    t.index ["queue", "priority", "run_at", "id"], name: "que_poll_idx", where: "((finished_at IS NULL) AND (expired_at IS NULL))"
    t.check_constraint "(char_length(last_error_message) <= 500) AND (char_length(last_error_backtrace) <= 10000)", name: "error_length"
    t.check_constraint "(jsonb_typeof(data) = 'object'::text) AND ((NOT (data ? 'tags'::text)) OR ((jsonb_typeof((data -> 'tags'::text)) = 'array'::text) AND (jsonb_array_length((data -> 'tags'::text)) <= 5) AND que_validate_tags((data -> 'tags'::text))))", name: "valid_data"
    t.check_constraint "char_length(queue) <= 100", name: "queue_length"
    t.check_constraint "jsonb_typeof(args) = 'array'::text", name: "valid_args"
    t.check_constraint nil, name: "job_class_length"
  end
```

(btw, why `check_constraint` is nil?)

2021001000010_create_que_schema.rb:
```ruby
class CreateQueSchema < ActiveRecord::Migration[6.1]
  def up
    Que.migrate!(version: 4)
  end

  def down
    Que.migrate!(version: 0)
  end
end
```

what i have:
```
ruby '2.7.1'
gem 'rails', '~> 6.1.3'
gem 'que', github: 'que-rb/que', tag: 'v1.0.0.beta4'
```

`gem 'que', github: 'que-rb/que', branch: 'master'` has this bug also

UPD: switched to `config.active_record.schema_format = :sql` as temporary solution

**Comment by yurgen93** [comment]
@a0s Maybe it's not a issue. Cause README says 

> If you're using ActiveRecord to dump your database's schema, please set your schema_format to :sql so that Que's table structure is managed correctly. This is a good idea regardless, as the :ruby schema format doesn't support many of PostgreSQL's advanced features.

**Comment by a0s** [comment]
@yurgen93 seems true
