### ISSUE TITLE
Deprecation warning with Rails 7.1

### ISSUE THREAD

**Issue by fragkakis** [que-rb/que#425]
Hello, thank you for the library!

With rails 7.1 I get the following deprecation warning:

```
WarningHandlers::Rails::Deprecation: DEPRECATION WARNING: `clear_active_connections!` currently only applies to connection pools in the current role (`writing`). In Rails 7.2, this method will apply to all known pools, regardless of role. To affect only those connections belonging to a specific role, pass the role name as an argument. To switch to the new behavior, pass `:all` as the role name. (called from run_job_middleware at (eval):11)
```

The stack trace is the following:

```
  "/home/workable/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/abstract/connection_handler.rb:187:in `clear_active_connections!'",
      "/home/workable/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/connection_handling.rb:321:in `clear_active_connections!'",
      "/home/workable/app/vendor/bundle/ruby/3.2.0/gems/que-2.3.0/lib/que/active_record/connection.rb:45:in `call'",
      "/home/workable/app/vendor/bundle/ruby/3.2.0/gems/que-2.3.0/lib/que/utils/middleware.rb:36:in `invoke_middleware'",
      "(eval):11:in `run_job_middleware'",
      "/home/workable/app/vendor/bundle/ruby/3.2.0/gems/que-2.3.0/lib/que/worker.rb:103:in `work_job'",
      "/home/workable/app/vendor/bundle/ruby/3.2.0/gems/que-2.3.0/lib/que/worker.rb:76:in `work_loop'",
      "/home/workable/app/vendor/bundle/ruby/3.2.0/gems/que-2.3.0/lib/que/worker.rb:46:in `block in initialize'",
      "/home/workable/app/vendor/bundle/ruby/3.2.0/gems/logging-2.3.1/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'"
```

I noticed there are 2 occasions of `clear_active_connections!` called in que without an argument, so I guess both should be handled.

**Comment by fragkakis** [comment]
Closing, noticed the relevant [PR](https://github.com/que-rb/que/pull/423).

**Comment by fragkakis** [comment]
Reopening because the PR has not been merged.

**Comment by kaylareopelle** [comment]
Rails 7.2.0 was released on August 9, 2024, which dropped `clear_active_connections!`. This makes `que` incompatible with the latest version of Rails. Any update on when #423 might be merged?

**Comment by kaylareopelle** [comment]
Hi, @ZimbiX! There's a small way I can test out #423. 

I came across this issue due to test failures in [`opentelemetry-instrumentation-que`](https://github.com/open-telemetry/opentelemetry-ruby-contrib/tree/main/instrumentation/que) gem. 

When I run the tests for this gem with activerecord 7.2 and the branch for #423, the tests pass. Without it, they fail with the following message:
```
OpenTelemetry::Instrumentation::Que::processing a job that fails#test_0001_marks the span as failed:
NoMethodError: undefined method `clear_active_connections!' for ActiveRecord::Base:Class
    /bundle/ruby/3.2.0/gems/activerecord-7.2.0/lib/active_record/dynamic_matchers.rb:22:in `method_missing'
    /bundle/ruby/3.2.0/gems/que-2.3.0/lib/que/active_record/connection.rb:45:in `call'
    /bundle/ruby/3.2.0/gems/que-2.3.0/lib/que/utils/middleware.rb:36:in `invoke_middleware'
    (eval):11:in `run_job_middleware'
    test/opentelemetry/instrumentation/que_test.rb:91:in `block (3 levels) in <top (required)>'
```

**Comment by kaylareopelle** [comment]
Hi @ZimbiX! Have you had a chance to take another look at this issue/#423?

**Comment by Tabby** [comment]
If it helps, I've tested #423 with some of our services and it fixes the deprecation warnings without causing any issues that I've been able to see. Is there anything else any of us can do to help get it merged? It is blocking us from upgrading to Rails 7.2
